PI_2: &pi_2 1.57079632679

# links' lenght
cylinder_radius: &cr 0.07
cylinder_length: &cl 0.1
big_box_length: &bbl 0.4
big_box_width: &bbw 0.1
big_box_height: &bbh 0.1
small_box_length: 0.4
small_box_width: 0.05
small_box_height: 0.05
ball_radius: 0.05
pelvis_length: &pl 0.80
pelvis_width: &pw 0.45
pelvis_height: &ph 0.20

# legs
HipRoll_Ox: *pl
HipRoll_Oy: *pw
HipRoll_Oz: 0.0
HipRoll_roll: 0.0
HipRoll_pitch: *pi_2
HipRoll_yaw: 0.0

HipPitch_Ox: 0.0
HipPitch_Oy: *cr
HipPitch_Oz: 0.0
HipPitch_roll: *pi_2
HipPitch_pitch: 0.0
HipPitch_yaw: 0.0

UpperLeg_Ox: 0.0
UpperLeg_Oy: 0.0
UpperLeg_Oz: 0.0
UpperLeg_roll: 0.0
UpperLeg_pitch: 0.0
UpperLeg_yaw: 0.0

KneePitch_Ox: *bbl
KneePitch_Oy: 0.0
KneePitch_Oz: 0.0
KneePitch_roll: 0.0
KneePitch_pitch: 0.0
KneePitch_yaw: 0.0

LowerLeg_Ox: 0.0
LowerLeg_Oy: 0.0
LowerLeg_Oz: 0.0
LowerLeg_roll: 0.0
LowerLeg_pitch: 0.0
LowerLeg_yaw: 0.0

Ankle_Ox: *bbl
Ankle_Oy: 0.0
Ankle_Oz: 0.0
Ankle_roll: 0.0
Ankle_pitch: 0.0
Ankle_yaw: 0.0

# arms
ShoulderYaw_Ox: *pl
ShoulderYaw_Oy: *pw
ShoulderYaw_Oz: *ph
ShoulderYaw_roll: 0.0
ShoulderYaw_pitch: 0.0
ShoulderYaw_yaw: 0.0

ShoulderPitch_Ox: 0.0
ShoulderPitch_Oy: 0.0 
ShoulderPitch_Oz: *cl
ShoulderPitch_roll: *pi_2
ShoulderPitch_pitch: 0.0 
ShoulderPitch_yaw: 0.0

LowerArm_Ox: 0.0
LowerArm_Oy: 0.0
LowerArm_Oz: 0.0
LowerArm_roll: 0.0
LowerArm_pitch: 0.0
LowerArm_yaw: *pi_2

ElbowPitch_Ox: *bbl
ElbowPitch_Oy: 0.0 
ElbowPitch_Oz: 0.0
ElbowPitch_roll: 0.0
ElbowPitch_pitch: 0.0 
ElbowPitch_yaw: 0.0

UpperArm_Ox: 0.0
UpperArm_Oy: 0.0
UpperArm_Oz: 0.0
UpperArm_roll: 0.0
UpperArm_pitch: 0.0
UpperArm_yaw: 0.0

EndEffector_Ox: *bbl
EndEffector_Oy: 0.0
EndEffector_Oz: 0.0
EndEffector_roll: 0.0
EndEffector_pitch: 0.0
EndEffector_yaw: 0.0
