solver_options:
    regularization: 1e-2
    back_end: osqp
    
stack:
    - [wheel_1, wheel_2, wheel_3, wheel_4] #, l_arm, r_arm]
    - [Rolling_FL, Rolling_FR, Rolling_HL, Rolling_HR, Postural, Com, PelvisRot]

defaults:
    - &wheel_radius 0.124 
    
wheel_1:
    type: Cartesian
    distal_link: wheel_1
    base_link: world
    indices: [0, 1, 2]
    
wheel_2:
    type: Cartesian
    distal_link: wheel_2
    base_link: world
    indices: [0, 1, 2]
    
wheel_3:
    type: Cartesian
    distal_link: wheel_3
    base_link: world
    indices: [0, 1, 2]
    
wheel_4:
    type: Cartesian
    distal_link: wheel_4
    base_link: world
    indices: [0, 1, 2]

Rolling_FL:
    type: WheelRolling
    wheel_name: wheel_1
    lib_name: libcentauro_cartesio_addon.so
    wheel_radius: *wheel_radius
    weight: 1000.0

Rolling_FR:
    type: WheelRolling
    wheel_name: wheel_2
    lib_name: libcentauro_cartesio_addon.so
    wheel_radius: *wheel_radius
    weight: 1000.0

Rolling_HL:
    type: WheelRolling
    wheel_name: wheel_3
    lib_name: libcentauro_cartesio_addon.so
    wheel_radius: *wheel_radius
    weight: 1000.0

Rolling_HR:
    type: WheelRolling
    wheel_name: wheel_4
    lib_name: libcentauro_cartesio_addon.so
    wheel_radius: *wheel_radius
    weight: 1000.0    

l_arm:
    type: Cartesian
    distal_link: dagana_1_base
    base_link: world 
    indices: [0, 1, 2, 3, 4, 5]
    

r_arm:
    type: Cartesian
    distal_link: dagana_2_base
    base_link: world 
    indices: [0, 1, 2, 3, 4, 5]
    
    
Com:
    type: Com
    indices: [0, 1]
    weight: 10
    
Postural:
    type: Postural
    lambda: 0.1
    disabled_joints:
        - wheel_joint_1
        - wheel_joint_2
        - wheel_joint_3
        - wheel_joint_4
    
PelvisRot:
    type: Cartesian
    distal_link: pelvis
    weight: 10
    indices: [4, 5]
