solver_options:
    regularization: 1e-2
    back_end: osqp
    
stack:
    - [contact_1, contact_2, contact_3, contact_4, r_arm, l_arm, PelvisRot, Postural, Com]
    # - [Postural, Com, PelvisRot]

constraints: 
    - jlim
    - vlim
    - collision

jlim:
    type: JointLimits

vlim:
    type: VelocityLimits

collision:
    type: CollisionConstraint
    lib_name: libcartesio_collision_support.so
    bound_scaling: 0.1
    distance_threshold: 0.02
    detection_threshold: 0.10
    max_pairs: 60
    collision_urdf_path: $(ros2 pkg prefix --share kyon_urdf)/urdf/kyon_capsule.urdf
    collision_srdf_path: $(ros2 pkg prefix --share kyon_srdf)/srdf/kyon_capsule.srdf
    env_collision_links: [hip_pitch_1_link, hip_pitch_2_link, hip_pitch_3_link, hip_pitch_4_link] #, pelvis]
    infeasible_pair_weight: 0.01
    # weight: 100.0
    # pairs:
    #  - [dagana_2_base, pelvis]
    world:
     - name: floor
       type: halfspace
       normal: [0, 0, 1]
       position: [0, 0, 0.0]
       disabled_collisions: [knee_pitch_1_link, knee_pitch_2_link, knee_pitch_3_link, knee_pitch_4_link]

contact_1:
    type: Cartesian
    distal_link: contact_1
    base_link: world
    indices: [0, 1, 2]
    
contact_2:
    type: Cartesian
    distal_link: contact_2
    base_link: world
    indices: [0, 1, 2]
    
contact_3:
    type: Cartesian
    distal_link: contact_3
    base_link: world
    indices: [0, 1, 2]
    
contact_4:
    type: Cartesian
    distal_link: contact_4
    base_link: world
    indices: [0, 1, 2]
    

l_arm:
    type: Cartesian
    distal_link: dagana_1_base
    base_link: world 
    # indices: [0, 1, 2, 3, 5]
    use_local_subtasks: true
    lambda: 0.1
    

r_arm:
    type: Cartesian
    distal_link: dagana_2_base
    base_link: world 
    # indices: [0, 1, 2, 3, 5]
    use_local_subtasks: true
    lambda: 0.1
    
    
Com:
    type: Com
    indices: [0, 1, 2]
    weight: [0, 0, 0]
    
Postural:
    type: Postural
    lambda: 0.05
    weight: 0.001
    
PelvisRot:
    type: Cartesian
    distal_link: pelvis
    weight: 0.001
    indices: [4, 5]
