[metadata]
name = kyon_isaac
version = 1.0.0
author = Arturo Laurenzi
author_email = arturo.laurenzi@iit.it
description = Python package to simulate the IIT Kyon robot in the Isaac Lab environment.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://none
project_urls =
    Bug Tracker = https://none
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find_namespace:
include_package_data = True
python_requires = >=3.8
install_requires =

    

[options.packages.find]
where = src

[options.entry_points]
console_scripts =
