# assign childclass attribute to subtrees (e.g. for applying proper friction values to joints)
childclass:
  shoulder_yaw_1_link: kyon_arm
  shoulder_yaw_2_link: kyon_arm
  hip_roll_1_link: kyon_leg
  hip_roll_2_link: kyon_leg
  hip_roll_3_link: kyon_leg
  hip_roll_4_link: kyon_leg
  ankle_yaw_1_link: kyon_ankle
  ankle_yaw_2_link: kyon_ankle
  ankle_yaw_3_link: kyon_ankle
  ankle_yaw_4_link: kyon_ankle
  wheel_1: kyon_wheel
  wheel_2: kyon_wheel
  wheel_3: kyon_wheel
  wheel_4: kyon_wheel

# define initial position
q_init:
  hip_roll_1: 0.15
  hip_pitch_1: -0.7
  knee_pitch_1: 1.4
  hip_roll_2: -0.15
  hip_pitch_2: 0.7
  knee_pitch_2: -1.4
  hip_roll_3: -0.15
  hip_pitch_3: -0.7
  knee_pitch_3: 1.4
  hip_roll_4: 0.15
  hip_pitch_4: 0.7
  knee_pitch_4: -1.4
  ankle_yaw_1: 0.0
  ankle_yaw_2: 0.0
  ankle_yaw_3: 0.0
  ankle_yaw_4: 0.0
  shoulder_yaw_1: 0.0
  shoulder_pitch_1: 1.0
  elbow_pitch_1: 2.1
  wrist_pitch_1: 0.7
  wrist_yaw_1: 0.0
  shoulder_yaw_2: 0.0
  shoulder_pitch_2: -1.0
  elbow_pitch_2: -2.1
  wrist_pitch_2: -0.7
  wrist_yaw_2: 0.0