x-default-isaac-lab-template-environment: &default-isaac-lab-template-environment
  - OMNI_KIT_ALLOW_ROOT=1
  - DISPLAY
  - XAUTHORITY=/root/.Xauthority
  - ACCEPT_EULA=Y

x-default-isaac-lab-template-deploy: &default-isaac-lab-template-deploy
  resources:
    reservations:
      devices:
        - driver: nvidia
          count: all
          capabilities: [ gpu ]

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $XAUTHORITY:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.xbot2_isaac:/tmp/.xbot2_isaac:rw
      - ../../../:/workspace/iit-kyon-ros-pkg:rw
    network_mode: host
    restart: always
    environment: *default-isaac-lab-template-environment
    deploy: *default-isaac-lab-template-deploy
    # This is the entrypoint for the container
    stdin_open: true
    tty: true
    entrypoint: ''
    command: bash -ic 'pip install -e /workspace/iit-kyon-ros-pkg/kyon_isaac/python; bash -i'
